# vm1 docker-compose 文件，共三个容器，orderer,peer和cli

version: '2.1'

volumes:
  orderer1.template.com:
  peer0.org1.template.com:

networks:
  template:
    name: fabric_template
  
services:

  orderer1.template.com:
    container_name: orderer1
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../organizations/ordererOrganizations/template.com/orderers/orderer1.template.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/template.com/orderers/orderer1.template.com/tls/:/var/hyperledger/orderer/tls
        - orderer1.template.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 9443:9443
    # 此处需要添加其他docker容器所在ip
    extra_hosts:
      - "orderer1.template.com:10.1.2.11"
      - "orderer2.template.com:10.1.2.12"
      - "orderer3.template.com:10.1.2.13"
    networks:
      - template


  peer0.org1.template.com:
    container_name: peer0.org1
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_template
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.org1.template.com
      - CORE_PEER_ADDRESS=peer0.org1.template.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.template.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.template.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.template.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.template.com:9444
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ../organizations/peerOrganizations/org1.template.com/peers/peer0.org1.template.com/msp:/etc/hyperledger/fabric/msp
        - ../organizations/peerOrganizations/org1.template.com/peers/peer0.org1.template.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.template.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
      - 9444:9444
    # 此处需要添加其他docker容器所在ip
    extra_hosts:
      - "orderer1.template.com:10.1.2.11"
      - "orderer2.template.com:10.1.2.12"
      - "orderer3.template.com:10.1.2.13"
    networks:
      - template

# 此处相比test-net.yaml变化较大
# 由于此cli只为orderer1 与peer0.org1工作，无需进行切换
# 因此可以预先导入后续会用到的一些环境变量
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      # 此cli为peer0 org1 专用，因此导入一些必要的环境变量
      - ORDERER_ADDRESS=orderer1.template.com
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/template.com/orderers/orderer1.template.com/msp/tlscacerts/tlsca.template.com-cert.pem
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.template.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.template.com/peers/peer0.org1.template.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.template.com/peers/peer0.org1.template.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.template.com/peers/peer0.org1.template.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/org1.template.com/users/Admin@org1.template.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        # 导入通道信息
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        # 导入证书
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        # 导入脚本
        - ../remote-scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/remote-scripts
        - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        # 导入链码
        - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
    depends_on:
      - peer0.org1.template.com
    networks:
      - template
